### ISSUE TITLE
Sometimes need to manually reload NGINX for this to work

### ISSUE THREAD

**Issue by cjacky475** [Wowu/docker-rollout#30]
My `docker-compose.yml` is:

```
services:
  backend:
    image: backend-api
    restart: unless-stopped
    networks:
    - proxyNetwork
  frontend:
    image: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxyNetwork
  <...>
```

1. Running `docker rollout -f docker-compose.yml backend` results in it actually working every second time, not sure why. First time I call this the frontend cannot call the backend, it says 404, second time I use `docker rollout ...` then it starts working. And it only works every second time, not sure why. The time it's not working I have to call `docker compose exec frontend /usr/sbin/nginx -s reload` for it to work.
2. Also, if I wanted to reload frontend image as well, I have to extract nginx into different service, right? Since I cannot set port for the image to be reloaded.

Cheers for the help.
