### ISSUE TITLE
I'd like to request a minimal example demonstrating how to perform zero-downtime deployment using docker rollout with Nginx and Rails.

### ISSUE THREAD

**Issue by activeliang** [Wowu/docker-rollout#9]
```yml
version: "3.9"
services:
  web:
    image: activeliang/rtr_wms-web
    environment:
      VITE_RUBY_HOST: 0.0.0.0
      RAILS_ENV: production
    volumes:
      - /tmp/sockets/rtr_wms:/rtr_wms/tmp/sockets
```

Hello, the code above is part of my docker-compose.yml file, where my Nginx server runs on the host machine and the Rails application runs inside a container. When I specify to scale the Rails application to two instances using the docker rollout, they both point to /rtr_wms/tmp/sockets/puma.sock which causes a conflict, and one of the apps restarts as a result.

My issue is that I'm not sure how to balance the relationship between Nginx and Rails. Therefore, I'd like to request a minimal example demonstrating how to perform zero-downtime deployment using docker rollout with Nginx and Rails.
